FROM golang:1.25.6 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o marketdata-producer ./cmd/producer/main.go


FROM debian:bullseye-slim

COPY --from=builder /build/marketdata-producer /marketdata-producer

WORKDIR /

EXPOSE 50051

CMD ["./marketdata-producer"]