services:
  agregator:
    image: marketdata-agregator
    container_name: agregator
    restart: unless-stopped
    environment:
      - DATABASE_DSN=postgresql://postgres:test@timescaledb:5432/market_data
      - INVEST_TOKEN=t.R0UYpK2-ZNZgpdyWuKWpcNrpyTMllXFUqP777_2fgRR8SZ-U_25BDMDT6xXRzXoyf_urJ6-bTm7yt3j-2z81WQ
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - main

  producer:
    image: marketdata-producer
    container_name: producer
    restart: unless-stopped
    environment:
      - DATABASE_DSN=postgresql://postgres:test@timescaledb:5432/market_data
      - INVEST_TOKEN=t.R0UYpK2-ZNZgpdyWuKWpcNrpyTMllXFUqP777_2fgRR8SZ-U_25BDMDT6xXRzXoyf_urJ6-bTm7yt3j-2z81WQ
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./cmd/producer/instruments.json:/cmd/producer/instruments:ro
    networks:
      - main

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=market_data
      - TS_TUNE_MEMORY=4GB 
      - TS_TUNE_NUM_CPUS=4
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - main

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "george.ermekov@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1111"
    ports:
      - "5433:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - main
    logging:
      options:
        max-size: 10m

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pg_data:
  redis-data:
  pgadmin_data:
  rabbitmq_data:
