// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/instruments": {
            "get": {
                "description": "Get a financial instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instruments"
                ],
                "summary": "Get instrument",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Instrument"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing financial instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instruments"
                ],
                "summary": "Update instrument",
                "parameters": [
                    {
                        "description": "Instrument data with UID",
                        "name": "instrument",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.instrumentPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Instrument"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new financial instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instruments"
                ],
                "summary": "Create instrument",
                "parameters": [
                    {
                        "description": "Instrument data",
                        "name": "instrument",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.instrumentPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Instrument"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a financial instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instruments"
                ],
                "summary": "Delete instrument",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/bonds": {
            "put": {
                "description": "Update a bond instrument and its base data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Update bond",
                "parameters": [
                    {
                        "description": "Bond data with UID",
                        "name": "bond",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.bondPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Bond"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a bond instrument along with its base instrument record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Create bond",
                "parameters": [
                    {
                        "description": "Bond data",
                        "name": "bond",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.bondPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Bond"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/bonds/{uid}": {
            "get": {
                "description": "Get a bond instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Get bond",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bond UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a bond instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Delete bond",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bond UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/currencies": {
            "put": {
                "description": "Update a currency instrument and its base data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Update currency",
                "parameters": [
                    {
                        "description": "Currency data with UID",
                        "name": "currency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.currencyPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Currency"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a currency instrument along with its base instrument record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Create currency",
                "parameters": [
                    {
                        "description": "Currency data",
                        "name": "currency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.currencyPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Currency"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/currencies/{uid}": {
            "get": {
                "description": "Get a currency instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Get currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a currency instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Delete currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/etfs": {
            "put": {
                "description": "Update an ETF instrument and its base data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "etfs"
                ],
                "summary": "Update ETF",
                "parameters": [
                    {
                        "description": "ETF data with UID",
                        "name": "etf",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.etfPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Etf"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create an ETF instrument along with its base instrument record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "etfs"
                ],
                "summary": "Create ETF",
                "parameters": [
                    {
                        "description": "ETF data",
                        "name": "etf",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.etfPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Etf"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/etfs/{uid}": {
            "get": {
                "description": "Get an ETF instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "etfs"
                ],
                "summary": "Get ETF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETF UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an ETF instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "etfs"
                ],
                "summary": "Delete ETF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETF UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/futures": {
            "put": {
                "description": "Update a future instrument and its base data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "futures"
                ],
                "summary": "Update future",
                "parameters": [
                    {
                        "description": "Future data with UID",
                        "name": "future",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.futurePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Future"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a future instrument along with its base instrument record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "futures"
                ],
                "summary": "Create future",
                "parameters": [
                    {
                        "description": "Future data",
                        "name": "future",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.futurePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Future"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/futures/{uid}": {
            "get": {
                "description": "Get a future instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "futures"
                ],
                "summary": "Get future",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Future UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a future instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "futures"
                ],
                "summary": "Delete future",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Future UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/shares": {
            "put": {
                "description": "Update a share instrument and its base data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shares"
                ],
                "summary": "Update share",
                "parameters": [
                    {
                        "description": "Share data with UID",
                        "name": "share",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.sharePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Share"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a share instrument along with its base instrument record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shares"
                ],
                "summary": "Create share",
                "parameters": [
                    {
                        "description": "Share data",
                        "name": "share",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_interfaces_http.sharePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_instruments.Share"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/instruments/shares/{uid}": {
            "get": {
                "description": "Get a share instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shares"
                ],
                "summary": "Get share",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a share instrument by UID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shares"
                ],
                "summary": "Delete share",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Share UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/candles": {
            "get": {
                "description": "Get candles for an instrument within a time range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "candles"
                ],
                "summary": "Get candles range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Candle interval in seconds",
                        "name": "interval_seconds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Candle"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a single candle record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "candles"
                ],
                "summary": "Add candle",
                "parameters": [
                    {
                        "description": "Candle data",
                        "name": "candle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_marketdata.Candle"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/candles/batch": {
            "post": {
                "description": "Add multiple candle records in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "candles"
                ],
                "summary": "Add candles batch",
                "parameters": [
                    {
                        "description": "Array of candle data",
                        "name": "candles",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Candle"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/candles/last": {
            "get": {
                "description": "Get the last N candles for an instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "candles"
                ],
                "summary": "Get last candles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Candle interval in seconds",
                        "name": "interval_seconds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of candles to retrieve",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Candle"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/orderbooks": {
            "get": {
                "description": "Get order book snapshots for an instrument within a time range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orderbooks"
                ],
                "summary": "Get order books range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order book depth",
                        "name": "depth",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookSnapshot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a single order book snapshot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orderbooks"
                ],
                "summary": "Add order book",
                "parameters": [
                    {
                        "description": "Order book snapshot data",
                        "name": "orderbook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookSnapshot"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/orderbooks/batch": {
            "post": {
                "description": "Add multiple order book snapshots in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orderbooks"
                ],
                "summary": "Add order books batch",
                "parameters": [
                    {
                        "description": "Array of order book snapshot data",
                        "name": "orderbooks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookSnapshot"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/orderbooks/last": {
            "get": {
                "description": "Get the last N order book snapshots for an instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orderbooks"
                ],
                "summary": "Get last order books",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Order book depth",
                        "name": "depth",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of snapshots to retrieve",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookSnapshot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/trades": {
            "get": {
                "description": "Get trades for an instrument within a time range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trades"
                ],
                "summary": "Get trades range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Trade"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a single trade record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trades"
                ],
                "summary": "Add trade",
                "parameters": [
                    {
                        "description": "Trade data",
                        "name": "trade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main_internal_domain_entity_marketdata.Trade"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/trades/batch": {
            "post": {
                "description": "Add multiple trade records in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trades"
                ],
                "summary": "Add trades batch",
                "parameters": [
                    {
                        "description": "Array of trade data",
                        "name": "trades",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Trade"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/marketdata/trades/last": {
            "get": {
                "description": "Get the last N trades for an instrument",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trades"
                ],
                "summary": "Get last trades",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instrument UID",
                        "name": "instrument_uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of trades to retrieve",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main_internal_domain_entity_marketdata.Trade"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_interfaces_http.bondPayload": {
            "type": "object",
            "properties": {
                "aci_value": {
                    "type": "number"
                },
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "nominal": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "internal_interfaces_http.currencyPayload": {
            "type": "object",
            "properties": {
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "internal_interfaces_http.etfPayload": {
            "type": "object",
            "properties": {
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "min_price_increment": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "internal_interfaces_http.futurePayload": {
            "type": "object",
            "properties": {
                "asset_type": {
                    "type": "string"
                },
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "min_price_increment": {
                    "type": "number"
                },
                "min_price_increment_amount": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "internal_interfaces_http.instrumentPayload": {
            "type": "object",
            "properties": {
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "internal_interfaces_http.sharePayload": {
            "type": "object",
            "properties": {
                "class_code": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.AssetType": {
            "type": "string",
            "enum": [
                "TYPE_INDEX",
                "TYPE_COMMODITY",
                "TYPE_SECURITY",
                "TYPE_CURRENCY"
            ],
            "x-enum-varnames": [
                "AssetTypeIndex",
                "AssetTypeCommodity",
                "AssetTypeSecurity",
                "AssetTypeCurrency"
            ]
        },
        "main_internal_domain_entity_instruments.Bond": {
            "type": "object",
            "properties": {
                "aciValue": {
                    "type": "number"
                },
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "nominal": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.Currency": {
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.Etf": {
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "minPriceIncrement": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.Future": {
            "type": "object",
            "properties": {
                "assetType": {
                    "$ref": "#/definitions/main_internal_domain_entity_instruments.AssetType"
                },
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "minPriceIncrement": {
                    "type": "number"
                },
                "minPriceIncrementAmount": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.Instrument": {
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_instruments.Share": {
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "logoURL": {
                    "type": "string"
                },
                "lot": {
                    "type": "integer"
                },
                "ticker": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_marketdata.Candle": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "instrumentUID": {
                    "type": "string"
                },
                "intervalSeconds": {
                    "type": "integer"
                },
                "lastTradeAt": {
                    "type": "string"
                },
                "low": {
                    "type": "number"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "open": {
                    "type": "number"
                },
                "periodStart": {
                    "type": "string"
                },
                "volumeBuyLots": {
                    "type": "integer"
                },
                "volumeLots": {
                    "type": "integer"
                },
                "volumeSellLots": {
                    "type": "integer"
                }
            }
        },
        "main_internal_domain_entity_marketdata.OrderBookLevel": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "main_internal_domain_entity_marketdata.OrderBookSnapshot": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookLevel"
                    }
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main_internal_domain_entity_marketdata.OrderBookLevel"
                    }
                },
                "depth": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "instrumentUID": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "snapshotAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_marketdata.Trade": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "instrumentUID": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "price": {
                    "type": "number"
                },
                "quantityLots": {
                    "type": "integer"
                },
                "side": {
                    "$ref": "#/definitions/main_internal_domain_entity_marketdata.TradeSide"
                },
                "tradedAt": {
                    "type": "string"
                }
            }
        },
        "main_internal_domain_entity_marketdata.TradeSide": {
            "type": "string",
            "enum": [
                "BUY",
                "SELL"
            ],
            "x-enum-varnames": [
                "TradeSideBuy",
                "TradeSideSell"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
